const page=document.body.dataset.page;
const content={
 about:{eyebrow:'Our story',title:'Healing is possible. You don’t have to do it alone.',text:'At SHIFT Healing Center, we provide trauma-informed, evidence-based care that helps you feel better, know yourself and live with greater ease and purpose.',button:'Meet our team',href:'team.html'},
 services:{eyebrow:'Care built around you',title:'How we can help',text:'Individual, couples and group therapy, psychiatry, and relationships and recovery support—connected in one thoughtful practice.',button:'Request a consultation',href:'contact.html'},
 specialties:{eyebrow:'Specialized support',title:'Care for the moments that matter',text:'Explore focused support for anxiety, depression, trauma, ADHD, grief, burnout, relationships, major life transitions and recovery.',button:'Find the right care',href:'contact.html'},
 team:{eyebrow:'Experienced therapists. Real connection.',title:'A diverse team united by compassion and expertise.',text:'Our clinicians bring deep clinical experience, warmth and a shared commitment to your healing.',button:'Get matched',href:'contact.html'},
 resources:{eyebrow:'Knowledge can be a beginning',title:'Resources for understanding and growth',text:'Practical guidance and thoughtful information to support your mental health between sessions and before care begins.',button:'Explore services',href:'services.html'},
 contact:{eyebrow:'Taking the first step can feel big',title:'We make it simple.',text:'Reach out today to get matched with the right therapist and begin your healing journey.',button:'Send your request',href:'#form'}
};
const c=content[page];
const nav=['home','about','services','specialties','team','resources','contact'].map(n=>`<a class="${n===page?'active':''}" href="${n==='home'?'index':n}.html">${n==='team'?'Our Team':n==='specialties'?'What We Treat':n[0].toUpperCase()+n.slice(1)}</a>`).join('');
const form=page==='contact'?`<form id="form" class="contact-form"><label>Full name<input required name="name"></label><label>Email address<input required type="email" name="email"></label><label>How can we help?<textarea required name="message"></textarea></label><button class="btn teal" type="submit">Send message</button></form>`:'';
document.querySelector('#shell').innerHTML=`<header class="site-header"><div class="container nav"><a class="logo" href="index.html"><span class="logo-mark">S</span><span class="logo-text"><strong>SHIFT</strong><small>HEALING CENTER</small></span></a><button class="menu-toggle" aria-label="Open menu">☰</button><nav class="nav-links">${nav}</nav><a class="btn" href="contact.html">Get started</a></div></header><main><section class="page-hero"><div class="container"><div class="eyebrow">${c.eyebrow}</div><h1>${c.title}</h1><p>${c.text}</p></div></section><section class="section"><div class="container"><div class="content-card"><div class="image-space" style="min-height:280px;margin-bottom:35px">PAGE IMAGE SPACE<br>Replace with your final photo</div><h2>${c.title}</h2><p>${c.text}</p>${form||`<a class="btn teal" style="margin-top:25px" href="${c.href}">${c.button}</a>`}</div></div></section></main><footer class="site-footer"><div class="container"><div class="footer-grid"><div><div class="logo"><span class="logo-mark">S</span><span class="logo-text"><strong>SHIFT</strong><small>HEALING CENTER</small></span></div></div><div><h3>Explore</h3><a href="about.html">About</a><a href="services.html">Services</a></div><div><h3>Support</h3><a href="resources.html">Resources</a><a href="contact.html">Contact</a></div><div><h3>Contact</h3><a href="tel:+16192898882">(619) 289-8882</a></div></div><div class="copyright">© 2026 SHIFT Healing Center.</div></div></footer>`;
document.querySelectorAll('.logo').forEach(logo=>{logo.innerHTML='<img class="brand-logo" src="assets/logo.png" alt="SHIFT Healing Center">';});
document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.nav-links').classList.toggle('open'));
document.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();alert('Form design is working. Connect it to your email service before launch.');});
